##
## Aporeto
##
[[constraint]]
  name = "github.com/aporeto-inc/trireme-csr"
  branch = "master"

[[constraint]]
  name = "github.com/aporeto-inc/trireme-statistics"
  branch = "master"

[[constraint]]
  name = "github.com/aporeto-inc/trireme-lib"
  version  = "^8.0.0"

[[override]]
  name = "github.com/aporeto-inc/netlink-go"
  version = "^1.4.0"

# the release version (v0.1.0)is too old, so we need to
# go to master right now
[[override]]
  name = "github.com/bvandewalle/go-ipset"
  branch = "master"

[[constraint]]
  name = "github.com/aporeto-inc/kubepox"
  branch = "master"


##
## Kubernetes
##
[[constraint]]
  name = "k8s.io/client-go"
  version = "^6.0.0"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"


##
## 3rd Party
##
[[constraint]]
  name = "github.com/spf13/pflag"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^1.5.0"


##
## Prunes
##
[prune]
  go-tests = true
  unused-packages = true
